name: Build and Deploy Jekyll site

on:
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4'
          bundler-cache: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # or your preferred version

      - name: Create Python venv & install jupyter
        run: |
          python -m venv jupyter_env
          source jupyter_env/bin/activate
          pip install --upgrade pip
          pip install jupyter

      - name: Install Imagemagick
        run: sudo apt-get update && sudo apt-get install -y imagemagick

      - name: Install dependencies (ruby)
        run: bundle install

      - name: Build site
        run: |
          source jupyter_env/bin/activate
          bundle exec jekyll build --incremental

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: gh-pages
          force_orphan: true
          cname: opdc.kr